# Generated by Django 5.1 on 2024-08-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PRODUCT',
        ),
    ]
