# Generated by Django 5.1 on 2024-09-09 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0010_admin_appointment_appointment_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APPOINTMENT_DETAILS',
        ),
    ]
