# Generated by Django 5.1 on 2024-09-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0011_delete_appointment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPOINTMENT_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('soil_condition', models.CharField(max_length=200)),
                ('soil_fertility', models.IntegerField()),
                ('recommended_crop', models.CharField(max_length=200)),
                ('Nitrogen', models.CharField(max_length=200)),
                ('Phosphorus', models.CharField(max_length=200)),
                ('Potassium', models.CharField(max_length=200)),
                ('other_suggestions', models.CharField(max_length=1000)),
            ],
        ),
    ]
