# Generated by Django 5.1 on 2024-09-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0012_appointment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='exam',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
