# Generated by Django 5.1 on 2024-09-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0014_remove_appointment_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APPOINTMENT_DETAILS',
        ),
    ]
