# Generated by Django 5.1 on 2024-09-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0018_appointment_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APPOINTMENT_DETAILS',
        ),
    ]
