# Generated by Django 5.1 on 2024-09-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0020_appointment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('buy_method', models.CharField(max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
